
server:
  port: ${PORT:8080}

spring:
  datasource:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

promotions:
  discountStrategy: ${PROMO_DISCOUNT_STRATEGY:LOWEST_VALUE}
  cart:
    triggerAmount: ${CART_PROMO_TRIGGER:12}
    discountPercentage: ${CART_PROMO_DISCOUNT_PERCENTAGE:25}
  item:
    triggerQty: ${ITEM_PROMO_TRIGGER:3}
    triggerItemCategory: ${ITEM_PROMO_TRIGGER_CATEGORY:TOPPING_OR_SIDE}
    discountPercentage: ${ITEM_PROMO_DISCOUNT_PERCENTAGE:100}
